---
driver_config:
  require_chef_omnibus: latest

platforms:
- name: ubuntu-13.10
- name: debian-7.0
- name: centos-6.4

suites:
- name: default
  run_list:
  - recipe[collectd_test]
- name: collectd-server
  run_list:
  - recipe[collectd_test::server]
- name: collectd-client_graphite
  run_list:
  - recipe[collectd_test::client_graphite]
- name: collectd-client_collectd
  run_list:
  - recipe[collectd_test::client_collectd]
- name: collectd-plugin
  run_list:
  - recipe[collectd_test::plugin]
- name: collectd-data_bag_plugins
  run_list:
  - recipe[collectd::data_bag_plugins]
  attributes:
    collectd:
      plugins: ['df', 'load']
- name: collectd-authfile
  run_list:
    - recipe[collectd_test::authfile]
