# Author:: Greg Fitzgerald (greg@gregf.org)
# Copyright:: Copyright (c) 2014 Greg Fitzgerald
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'fileutils'
require 'tempfile'

action :create do
  file new_resource.authfile do
    owner 'root'
    group 'root'
    mode '0600'
    content "# This file is auto generated by chef, all edits will be lost\n\n"
    action :create_if_missing
  end

  c = ruby_block "Adding #{new_resource.username} to authfile" do
    block do
      begin
        ::File.open(new_resource.authfile, 'a') do |file|
          file.write("#{new_resource.username}: #{new_resource.password}\n")
        end
      rescue => e
        Chef::Application.fatal!("Could not create authfile due to #{e}!")
      end
    end
    not_if "grep -q '#{new_resource.username}:' #{new_resource.authfile}"
  end
  new_resource.updated_by_last_action(c.updated_by_last_action?)
end

action :remove do
  r = ruby_block "Removing #{new_resource.username} from authfile" do
    block do
      tmpfile = Tempfile.new('new_auth')

      ::File.open(new_resource.authfile, 'r').each_line do |line|
        next if line.match(/^(\s+)?#/)
        tmpfile << line unless line.match(new_resource.username)
      end

      tmpfile.close

      FileUtils.mv(tmpfile.path, new_resource.authfile) unless FileUtils.compare_file(new_resource.authfile, tmpfile.path)
    end
    only_if { ::File.exist?(new_resource.authfile) }
  end
  new_resource.updated_by_last_action(r.updated_by_last_action?)
end
